### ISSUE TITLE
Server Error / Error del Servidor

### ISSUE THREAD

**Issue by ram-on** [LibreScore/app-librescore#49]
I am always getting a "server error" whenever I try to download MSCZ/MP3/MIDI file.  Tested on both macOS and Linux on version v3.0.9.

**Comment by mhbackes** [comment]
I have the same error. It seems like something broke.

**Comment by Vlastbia** [comment]
MuseScore has patched the LibreScore App. The server will be down for the foreseeable future until Peter find a solution.

In the meantime you can download MIDI, MP3 and PDF using the [browser extension](https://github.com/LibreScore/dl-librescore#browser-extension).

**Comment by PeterNjeim** [comment]
Fixed in [v4.0.10](https://github.com/LibreScore/app-librescore/releases/tag/v4.0.10)

**Comment by benterris** [comment]
Hello, FYI I'm still having the issue on Linux with version `4.0.12` (`Server error (ID: bcdf848)`)

**Comment by PeterNjeim** [comment]
I'm aware, server is overloaded, working on many fixes right now

**Comment by PeterNjeim** [comment]
Fixed in [v5.0.1](https://github.com/LibreScore/app-librescore/releases/tag/v5.0.1)

**Comment by PeterNjeim** [comment]
Working on a fix, give me a week

**Comment by PeterNjeim** [comment]
Fixed in [v6.0.1](https://github.com/LibreScore/app-librescore/releases/tag/v6.0.1)

**Comment by PeterNjeim** [comment]
@eduardoortega1999 your issue is unrelated to this one, please make a new issue next time.

Your problem usually means MuseScore is blocking your network. Try using another network, such as a VPN or your phone's mobile data, let me know if it works

**Comment by eduardoortega1999** [comment]
Hi,
Sorry for the wrong subject. I have tried different routers, mobile phones, and VPNs but the problem persists.

![Image](https://github.com/user-attachments/assets/77ec3053-0186-4110-87af-6aad7656b0db)

**Comment by PeterNjeim** [comment]
@eduardoortega1999 let's move here: https://github.com/LibreScore/app-librescore/issues/62
